# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\serialWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 513)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.serialDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.serialDisplay.setGeometry(QtCore.QRect(20, 70, 761, 381))
        self.serialDisplay.setReadOnly(True)
        self.serialDisplay.setObjectName("serialDisplay")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(690, 10, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.messageLine = QtWidgets.QLineEdit(self.centralwidget)
        self.messageLine.setGeometry(QtCore.QRect(20, 10, 661, 41))
        self.messageLine.setObjectName("messageLine")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuBAUD = QtWidgets.QMenu(self.menubar)
        self.menuBAUD.setObjectName("menuBAUD")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionClear_Output = QtWidgets.QAction(MainWindow)
        self.actionClear_Output.setObjectName("actionClear_Output")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.BAUD300 = QtWidgets.QAction(MainWindow)
        self.BAUD300.setObjectName("BAUD300")
        self.BAUD1200 = QtWidgets.QAction(MainWindow)
        self.BAUD1200.setObjectName("BAUD1200")
        self.BAUD2400 = QtWidgets.QAction(MainWindow)
        self.BAUD2400.setObjectName("BAUD2400")
        self.BAUD4800 = QtWidgets.QAction(MainWindow)
        self.BAUD4800.setObjectName("BAUD4800")
        self.BAUD9600 = QtWidgets.QAction(MainWindow)
        self.BAUD9600.setObjectName("BAUD9600")
        self.BAUD19200 = QtWidgets.QAction(MainWindow)
        self.BAUD19200.setObjectName("BAUD19200")
        self.BAUD38400 = QtWidgets.QAction(MainWindow)
        self.BAUD38400.setObjectName("BAUD38400")
        self.BAUD57600 = QtWidgets.QAction(MainWindow)
        self.BAUD57600.setObjectName("BAUD57600")
        self.BAUD115200 = QtWidgets.QAction(MainWindow)
        self.BAUD115200.setObjectName("BAUD115200")
        self.menuFile.addAction(self.actionClear_Output)
        self.menuFile.addAction(self.actionQuit)
        self.menuBAUD.addAction(self.BAUD300)
        self.menuBAUD.addAction(self.BAUD1200)
        self.menuBAUD.addAction(self.BAUD2400)
        self.menuBAUD.addAction(self.BAUD4800)
        self.menuBAUD.addAction(self.BAUD9600)
        self.menuBAUD.addAction(self.BAUD19200)
        self.menuBAUD.addAction(self.BAUD38400)
        self.menuBAUD.addAction(self.BAUD57600)
        self.menuBAUD.addAction(self.BAUD115200)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBAUD.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sendButton.setText(_translate("MainWindow", "Send"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuBAUD.setTitle(_translate("MainWindow", "BAUD"))
        self.actionClear_Output.setText(_translate("MainWindow", "Clear Output"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.BAUD300.setText(_translate("MainWindow", "300"))
        self.BAUD1200.setText(_translate("MainWindow", "1200"))
        self.BAUD2400.setText(_translate("MainWindow", "2400"))
        self.BAUD4800.setText(_translate("MainWindow", "4800"))
        self.BAUD9600.setText(_translate("MainWindow", "9600"))
        self.BAUD19200.setText(_translate("MainWindow", "19200"))
        self.BAUD38400.setText(_translate("MainWindow", "38400"))
        self.BAUD57600.setText(_translate("MainWindow", "57600"))
        self.BAUD115200.setText(_translate("MainWindow", "115200"))

